### ISSUE TITLE
tqdm: Set size changed during iteration

### ISSUE THREAD

**Issue by samamorgan** [akaszynski/keepa#110] opened 2021-09-10 19:25 UTC
I'm seeing the following error intermittently while using this library. I've audited all requirements, and this is the only package I use that requires `tqdm`

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tqdm/_monitor.py", line 69, in run
    instances = self.get_instances()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tqdm/_monitor.py", line 49, in get_instances
    return [i for i in self.tqdm_cls._instances.copy()
  File "/usr/lib/python3.8/_weakrefset.py", line 92, in copy
    return self.__class__(self)
  File "/usr/lib/python3.8/_weakrefset.py", line 50, in __init__
    self.update(data)
  File "/usr/lib/python3.8/_weakrefset.py", line 119, in update
    for element in other:
  File "/usr/lib/python3.8/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

This package appears to only provide progress bars, so disabling them will likely fix the issue, but there's some sort of implementation problem here that keeps popping this error up.

**Comment by akaszynski** [comment] 2021-09-10 22:50
That's a strange error.  I'm not seeing where that would occur since we're only using `tqdm` by creating a progress bar and not iterating through an iterable.  Is that the full traceback?

**Comment by samamorgan** [comment] 2021-09-11 01:05
@akaszynski Yep, that's all I get. My code now uses `progress_bar=False` when querying, which should remove any use of tqdm, if I'm reading the source right.

I've seen this error a total of 45 times since implementation on March 12th. This process runs once daily, querying across ~200 products. That comes out to around a 25% failure rate.

The issue itself was a bit of a ghost considering the traceback, and I had to use `pipdeptree -fl` to find that this library alone uses tqdm.

**Comment by akaszynski** [comment] 2022-03-01 07:58
Closing this due to age. Please reopen if this occurs again. I'm guessing the issue is with `tqdm`.

**Closed by akaszynski** 2022-03-01 07:58 UTC
